version: "3.3"
services:
  backend:
    container_name: backend
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - redis
      - db
  redis:
    image: "redis:alpine"
    volumes:
      - redis:/data
  db:
    image: postgres:latest
    restart: always
    container_name: postgres
    ports:
      - 1234:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - postgres:/var/lib/postgresql/data

  nginx:
    build: ./nginx
    ports:
      - "80:80"
      - "8080:8080"
    depends_on:
      - backend
      
volumes:
  redis:
  postgres: